- file:
    path: /docker
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Docker API TLS key
  copy:
    dest: "{{ key_path }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ key }}"
  notify: "restart docker"

- name: Docker API TLS CA cert
  copy:
    dest: "{{ ca_path }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ ca }}"
  notify: "restart docker"

- name: Docker API TLS cert
  copy:
    dest: "{{ cert_path }}"
    owner: root
    group: root
    mode: 0600
    content: "{{ cert }}"
  notify: "restart docker"
