- name: install dependencies
  apt: name=git

- name: install letsencrypt client
  git: repo=https://github.com/letsencrypt/letsencrypt clone=yes force=yes dest=/opt/letsencrypt

- name: open port 80
  ufw: rule=allow port=80 proto=tcp

- name: check if nginx exists
  stat: path=/etc/init.d/nginx
  register: nginx_status

# Need this because otherwise letsencrypt can't bind to port 80
- name: stop nginx
  service: name=nginx state=stopped
  when: nginx_status.stat.exists

- name: install a cert
  shell: /opt/letsencrypt/certbot-auto certonly --standalone --agree-tos --email {{ cert_contact_email }} -d {{ cert_domains | join(",") }} --keep --non-interactive --preferred-challenges http-01 --expand

- name: start nginx
  service: name=nginx state=started
  when: nginx_status.stat.exists

- name: close port 80
  ufw: rule=allow port=80 proto=tcp delete=yes
