- name: install ufw
  apt: name=ufw

- name: open ports
  ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  with_items: "{{ open_ports }}"

- name: enable ufw
  ufw: state=enabled policy=deny
