# This module should be run once for each service/app on the servers
# It provisions a TLS cert and an nginx site for the relevant service

- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
      - raw: sudo apt-get -y update && sudo apt-get -y install python-simplejson
      - name: Gather facts
        setup:
  roles:
    - role: letsencrypt
      cert_contact_email: "{{ lookup('env','CERT_EMAIL') }}"
      cert_domains:
        - "{{ lookup('env', 'APP_DOMAIN') }}"

    - role: nginx_site
      app_domain: "{{ lookup('env', 'APP_DOMAIN') }}"
      app_port: "{{ lookup('env', 'APP_PORT') }}"
      https_certs_dir: "/etc/letsencrypt/live/{{ lookup('env', 'APP_DOMAIN') }}"
