- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
      - raw: sudo apt-get -y update && sudo apt-get -y install python-simplejson
      - name: Gather facts
        setup:
  roles:
    - { role: firewall }
    - { role: geerlingguy.nodejs, nodejs_version: '6.x' }
    - { role: letsencrypt, cert_contact_email: "{{ lookup('env','CERT_EMAIL') }}", cert_domain: "{{ lookup('env', 'DOMAIN') }}" }
    - { role: nginx, server_name: "{{ lookup('env', 'DOMAIN') }}", https_certs_dir: "/etc/letsencrypt/live/{{ lookup('env', 'DOMAIN') }}" }

    - role: node-app
      app_name: rabblerouser-core
      repo: https://github.com/rabblerouser/rabblerouser-core.git
      git_sha: "{{ lookup('env', 'CORE_APP_GIT_SHA') }}"
      env_vars:
        - "AWS_ACCESS_KEY_ID={{ lookup('env','CORE_AWS_ACCESS_KEY_ID') }}"
        - "AWS_SECRET_ACCESS_KEY={{ lookup('env','CORE_AWS_SECRET_ACCESS_KEY') }}"
        - "LISTENER_AUTH_TOKEN={{ lookup('env','CORE_LISTENER_AUTH_TOKEN') }}"
        - "DATABASE_URL={{ lookup('env','CORE_DATABASE_URL') }}"
        - "SESSION_SECRET={{ lookup('env','CORE_SESSION_SECRET') }}"
        - "STREAM_NAME={{ lookup('env','STREAM_NAME') }}"
        - "ARCHIVE_BUCKET={{ lookup('env','ARCHIVE_BUCKET') }}"

    - role: node-app
      app_name: rabblerouser-mailer
      repo: https://github.com/rabblerouser/rabblerouser-mailer.git
      git_sha: "{{ lookup('env', 'MAILER_APP_GIT_SHA') }}"
      env_vars:
        - "AWS_ACCESS_KEY_ID={{ lookup('env','MAILER_AWS_ACCESS_KEY_ID') }}"
        - "AWS_SECRET_ACCESS_KEY={{ lookup('env','MAILER_AWS_SECRET_ACCESS_KEY') }}"
        - "LISTENER_AUTH_TOKEN={{ lookup('env','MAILER_LISTENER_AUTH_TOKEN') }}"
        - "EMAIL_FROM_ADDRESS={{ lookup('env', 'MAILER_EMAIL_FROM_ADDRESS') }}"
