- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
      - raw: sudo apt-get -y update && sudo apt-get -y install python-simplejson
      - name: Gather facts
        setup:
  roles:
    - { role: firewall }
    - { role: angstwad.docker_ubuntu, docker_opts: '-H tcp://0.0.0.0:2375' }
    - { role: nginx }
