- hosts: all
  sudo: yes
  gather_facts: no
  pre_tasks:
      - raw: sudo apt-get -y update && sudo apt-get -y install python-simplejson
      - name: Gather facts
        setup:
  roles:
    - { role: firewall }
    - { role: geerlingguy.nodejs, nodejs_version: '6.x' }
    - { role: angstwad.docker_ubuntu }
    - { role: nginx }

    - role: node-app
      app_name: rabblerouser-core
      repo: https://github.com/rabblerouser/core.git
      git_sha: "{{ lookup('env', 'CORE_APP_GIT_SHA') }}"
      setup_command: "{{ (lookup('env', 'SEED_DATABASE') == 'true') | ternary('npm run --prefix backend seed','') }}"
      env_vars:
        - "AWS_ACCESS_KEY_ID={{ lookup('env','CORE_AWS_ACCESS_KEY_ID') }}"
        - "AWS_SECRET_ACCESS_KEY={{ lookup('env','CORE_AWS_SECRET_ACCESS_KEY') }}"
        - "LISTENER_AUTH_TOKEN={{ lookup('env','CORE_LISTENER_AUTH_TOKEN') }}"
        - "SESSION_SECRET={{ lookup('env','CORE_SESSION_SECRET') }}"
        - "STREAM_NAME={{ lookup('env','STREAM_NAME') }}"
        - "ARCHIVE_BUCKET={{ lookup('env','ARCHIVE_BUCKET') }}"

    - role: node-app
      app_name: rabblerouser-mailer
      repo: https://github.com/rabblerouser/mailer.git
      git_sha: "{{ lookup('env', 'MAILER_APP_GIT_SHA') }}"
      setup_command: ""
      env_vars:
        - "AWS_ACCESS_KEY_ID={{ lookup('env','MAILER_AWS_ACCESS_KEY_ID') }}"
        - "AWS_SECRET_ACCESS_KEY={{ lookup('env','MAILER_AWS_SECRET_ACCESS_KEY') }}"
        - "LISTENER_AUTH_TOKEN={{ lookup('env','MAILER_LISTENER_AUTH_TOKEN') }}"
        - "STREAM_NAME={{ lookup('env','STREAM_NAME') }}"
